---
streamlit:
  title: "RW-Buddy"
  tab_title: "RW-Buddy"
  logo: "./images/Microsoft_logo.png"
  page_icon: "./images/Microsoft_logo.png"
  avatar: "./images/openai.png"
  assistant_intro_message: "Hi there :wave:, I'm RW-buddy. How can I help?" 
  about: "This is an AI Agent to help remote workers get the fun back into their lives =)"
azure:
  dummy: "test"
